Frontend Notification Modal is Created
bounswe/bounswe2020group6 pull request #246
Opened 2020-12-13 21:14 UTC by UkcaGreen

Notification modal is created. 
In order to implement this following components are used:
- Modal component from Ant Design
- Notification component that is created from scratch

Screenshot:
![resim](https://user-images.githubusercontent.com/42381853/102024143-36010e80-3da1-11eb-99bc-9149de7845bc.png)

2020-12-14 15:49 UTC, UkcaGreen commented
I am planning to convert navigation links into buttons, what you think?

Example screenshot:
![resim](https://user-images.githubusercontent.com/42381853/102102486-ebcd6b00-3e3c-11eb-8ee7-abc8be50fea1.png)

2020-12-22 15:25 UTC, aliramazanmert commented
Again, after connecting to the backend, we can merge this pr.

2020-12-23 21:47 UTC, cemreefe requested changes
Everything seems to be correctly implemented. However this code is not connected to the backend and makes use of a dummy data. The request can be approved after the adequate backend connection.

2020-12-23 21:47 UTC, cemreefe commented on frontend/src/components/MainHeader/index.jsx
> +  const notifications = [
We should connect to the backend before merging, since the necessary endpoints are implemented since this push. I am requesting a review.

2020-12-26 19:58 UTC, aliramazanmert commented
We are expecting this new beautiful header buttons and notification modal(with backend connection and accepting/rejecting requests) to be ready asap.

2020-12-26 22:57 UTC, cemreefe approved these changes
I have reviewed the pr, there are no conflicts and the code seems fine. I am merging the branch.

2020-12-26 22:58 UTC, merged